[versions]
annotation-api          = "1.3.2"
apache-commons          = "3.18.0"
commons-cli             = "1.10.0"
flyway                  = "11.14.1"
gestalt                 = "0.35.5"
grpc                    = "1.75.0"
guice                   = "7.0.0"
inamik-text-tables      = "0.8"
jackson                 = "2.20.0"
jakarta-inject-api      = "2.0.1"
jakarta-xml-bind-api    = "4.0.4"
jansi                   = "2.4.2"
jline                   = "3.30.6"
jooq                    = "3.20.8"
log4j                   = "2.25.1"
lombok                  = "1.18.34"
mockito                 = "5.19.0"
openai-gpt3             = "0.18.2"
protobuf                = "4.32.1"
protobuf-plugin         = "0.9.5"
snakeyaml               = "2.4"
testng                  = "7.11.0"

[libraries]
annotation-api          = { module = "javax.annotation:javax.annotation-api", version.ref = "annotation-api" }
apache-commons          = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons" }
commons-cli             = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
flyway-core             = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-db-pg            = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
gestalt-core            = { module = "com.github.gestalt-config:gestalt-core", version.ref = "gestalt" }
gestalt-yaml            = { module = "com.github.gestalt-config:gestalt-yaml", version.ref = "gestalt" }
grpc-netty              = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-protobuf           = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-services           = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-stub               = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
guice                   = { module = "com.google.inject:guice", version.ref = "guice" }
inamik-text-tables      = { module = "com.github.inamik.text.tables:inamik-text-tables", version.ref = "inamik-text-tables" }
jackson-databind        = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jakarta-inject-api      = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }
jakarta-xml-bind-api    = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind-api" }
jansi                   = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jline                   = { module = "org.jline:jline", version.ref = "jline" }
jooq                    = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-meta               = { module = "org.jooq:jooq-meta", version.ref = "jooq" }
jooq-meta-extensions    = { module = "org.jooq:jooq-meta-extensions", version.ref = "jooq" }
jooq-codegen            = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
log4j-api               = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core              = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-jul               = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
log4j-slf4j-impl        = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
lombok                  = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito-core            = { module = "org.mockito:mockito-core", version.ref = "mockito" }
openai-gpt3             = { module = "com.theokanning.openai-gpt3-java:service", version.ref = "openai-gpt3" }
protoc                  = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-java           = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
snakeyaml               = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
testng                  = { module = "org.testng:testng", version.ref = "testng" }

[plugins]
protobuf                = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
