[versions]
annotation-api = "1.3.2"
apache-commons = "3.18.0"
gestalt = "0.35.5"
log4j = "2.20.0"
lombok = "1.18.34"
guice = "7.0.0"
inamik-text-tables = "0.8"
jackson = "2.20.0"
jakarta-inject-api = "2.0.1"
jansi = "2.4.2"
jline = "3.30.6"
mockito = "5.19.0"
snakeyaml = "2.4"
testng = "7.11.0"
openai-gpt3 = "0.18.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

apache-commons = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons" }

log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
log4j-jul = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }

annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "annotation-api" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
inamik-text-tables = { module = "com.github.inamik.text.tables:inamik-text-tables", version.ref = "inamik-text-tables" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }

jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jline = { module = "org.jline:jline", version.ref = "jline" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
testng = { module = "org.testng:testng", version.ref = "testng" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
openai-gpt3 = { module = "com.theokanning.openai-gpt3-java:service", version.ref = "openai-gpt3" }
gestalt-core = { module = "com.github.gestalt-config:gestalt-core", version.ref = "gestalt" }
gestalt-yaml = { module = "com.github.gestalt-config:gestalt-yaml", version.ref = "gestalt" }
